AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Deploys the metrics-server into an existing kubernetes cluster
  (qs-qwertyuiop).
Metadata:
  cfn-lint: { config: { ignore_checks: [W9002, W9003, W9004, W9006] } }
Parameters:
  EksClusterName:
    Type: String
Resources:
  MetricsServer:
    Type: AWSQS::Kubernetes::Resource
    UpdateReplacePolicy: Delete
    DeletionPolicy: Retain
    Properties:
      ClusterName: !Ref EksClusterName
      Namespace: kube-system
      Url: https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.4.1/components.yaml
Outputs:
  MetricsServer:
    Value: !Ref MetricsServer
