AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Deploys the metrics-server into an existing kubernetes cluster
  (qs-qwertyuiop).
Metadata:
  cfn-lint: { config: { ignore_checks: [W9002, W9003, W9004, W9006] } }
Parameters:
  EksClusterName:
    Type: String
Resources:
  MetricsServerHelmChart:
    # https://github.com/kubernetes-sigs/metrics-server/
    # https://artifacthub.io/packages/helm/metrics-server/metrics-server
    Type: AWSQS::Kubernetes::Helm
    Properties:
      ClusterID: !Ref EksClusterName
      Namespace: kube-system
      Repository: https://kubernetes-sigs.github.io/metrics-server/
      Chart: metrics-server/metrics-server
      Values:
        image.repository: public.ecr.aws/eks-distro/kubernetes-sigs/metrics-server
        nodeSelector.kubernetes\.io/os: linux
